import = ["~/dotfiles/.config/alacritty/custom.toml"]

[font]
size = 16
normal = { family = "MesloLGSDZ Nerd Font" }
italic = { family = "MesloLGSDZ Nerd Font", style = "Italic" }
bold = { family = "MesloLGSDZ Nerd Font", style = "Bold" }
offset.x = 0
offset.y = 0


# normal = { family = "JetBrainsMonoNL Nerd Font Mono" }
# italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
# bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }
# normal = { family = "Departure Mono" }
# italic = { family = "Departure Mono" }
# bold = { family = "Departure Mono" }
# normal = { family = "gg sans mono" }
# italic = { family = "gg sans mono" }
# bold = { family = "gg sans mono" }

#THEME
